spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.102:3306/product?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /product2

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  keyPath: C:/Users/leons/Desktop/job/iMooc1/coding-117/doc/h5.p12
  notifyUrl: http://kkllsc.natapp1.cc/product2/pay/notify